services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB:-postgres} -U ${POSTGRES_USER:-postgres}']
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 3s

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    # save sessions in case we need to restart redis
    command: ['redis-server', '--requirepass', 'tempPass0731!', '--save', '60', '1']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 3s

volumes:
  postgres_data: {}
  redis_data: {}
